### ISSUE TITLE
ProductSubcategory cannot be expanded

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/DP-500-Azure-Data-Analyst#55]
# Module: 3
#### Step: 33-34

Description of issue:

There is a part where it is asking us to expand a column to set up a relationship, however, that isn't an option for the column.
The instructions mention a DimProductSubcategory when the closest column is ProductSubcategoryKey

It seems to be an issue with a relationship in the source DB.

Repro steps:

Follow the lab steps

**Comment by markfitzqa** [comment]
Microsoft have only tested with a SQL database rather than a synapse dedicated database.  Synapse dedicated databases do not support foreign key constraints.  This is how power query decides to allow the productsubcategory and productcategory expand icons.    Need to ignore instructions 31-36 within that section.
