### ISSUE TITLE
Lab 9 RLS

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/DP-500-Azure-Data-Analyst#71]
# Lab 9 RLS
### Step: 5

Description of issue

Step: In the Members box, commence entering Salespeople_Australia.

Issue:  **Salespeople_Australia** is not exist in the ADD of cloudslise.

**Comment by shannonlindsay** [comment]
Hi Alex - the reason the task is optional is because it depends on the creation of a Salespeople_Australia security group. If you refer to the text directly above those instructions, you'll see:

"This task relies on the existence of a Salespeople_Australia security group in the tenant you are working in. This security group does NOT automatically exist in the tenant. If you have permissions on your tenant, you can follow the steps below. If you are using a tenant provided to you in training, you will not have the appropriate permissions to create security groups. Please read through the tasks, but note that you will not be able to complete them in the absence of the existence of the security group. After reading through, proceed to the Clean Up task."
